In [2]:
# Question 1:
import numpy as np
def array_to_list(array):
    return array.tolist()
A = np.array([[1, 2, 3, 4, 5],[11, 12, 13, 14, 15]])
array_to_list(A)

[[1, 2, 3, 4, 5], [11, 12, 13, 14, 15]]

In [4]:
# Question 2:

# method 1(manually):
import numpy as np
def the_sum_of_diagonal_elements1(array):
    shape = array.shape
    x = 0
    result = 0
    while x < shape[0]:
        result += array[x, x]
        x+= 1
    print("The sum of the diagonal elements of the given array is", result)

# method 2(diag function):
def the_sum_of_diagonal_elements2(array):
    result = 0
    for i in np.diag(array):
        result += i
    print("The sum of the diagonal elements of the given array is", result)

# method 3(trace function):
def the_sum_of_diagonal_elements3(array):
    print("The sum of the diagonal elements of the given array is",np.trace(array))


A = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])
the_sum_of_diagonal_elements1(A)
the_sum_of_diagonal_elements2(A)
the_sum_of_diagonal_elements3(A)

The sum of the diagonal elements of the given array is 65
The sum of the diagonal elements of the given array is 65
The sum of the diagonal elements of the given array is 65


In [5]:
# Question 3:
def get_values_higher_than_x(array):    
    result = []
    if array.ndim == 3:
        x = int(input("X = "))
        for i in range (Array.shape[0]):
            for j in range (Array.shape[1]):
                for n in range (Array.shape[2]):
                    if Array [i, j, n] > x:
                        result.append(Array [i, j, n],)
    if array.ndim == 2:
        x = int(input("X = "))
        for i in range (Array.shape[0]):
            for j in range (Array.shape[1]):
                if Array [i, j] > x:
                    result.append(Array [i, j],)
    if array.ndim == 1:
        x = int(input("X = "))
        for i in range (Array.shape[0]):
            if Array [i] > x:
                result.append(Array [i])
    print("The values which are higher than x are", result)
Array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])
get_values_higher_than_x(Array)

X = 5
The values which are higher than x are [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


In [15]:
# Question 4:
A = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])
B = np.array([[5, 6, 7, 8, 9],
                  [10, 11, 12, 13, 14],
                  [15, 16, 17, 18, 19],
                  [20, 21, 22, 23, 24],
                  [25, 26, 27, 28, 29]])
# method 1 (using built in function):
def array_addition1(array1, array2):
    return array1 + array2

# method 2 (using built in function):
def array_addition2(array1, array2):
    return np.add(array1,array2)
    
# method 3 (manually):
def array_addition3(array1, array2):
    array_result = array1
    for i in range (array1.shape[0]):
        for j in range (array1.shape[1]):
            array_result[i, j] = array1[i, j] + array2[i, j]
    return array_result
C1 = array_addition1(A, B)
C2 = array_addition2(A, B)
C3 = array_addition3(A, B)
print ("the result of the first method is", C1)
print ("the result of the second method is", C2)
print ("the result of the third method is", C3)

the result of the first method is [[ 6  8 10 12 14]
 [16 18 20 22 24]
 [26 28 30 32 34]
 [36 38 40 42 44]
 [46 48 50 52 54]]
the result of the second method is [[ 6  8 10 12 14]
 [16 18 20 22 24]
 [26 28 30 32 34]
 [36 38 40 42 44]
 [46 48 50 52 54]]
the result of the third method is [[ 6  8 10 12 14]
 [16 18 20 22 24]
 [26 28 30 32 34]
 [36 38 40 42 44]
 [46 48 50 52 54]]


In [2]:
# Question 5:
import numpy as np
def substracting_the_mean_of_each_row_from_each_element_in_it(array):
    array = array.astype(np.float64)
    print("This is an the initial array: ", a)
    for i in array:
        mean_row = np.mean(i)
        i -= mean_row
    print("This is the final array after substracting the mean of each row from each element in it", a)


a = np.random.randint(1, 22, (5,4))
substracting_the_mean_of_each_row_from_each_element_in_it(a)

This is an the initial array:  [[11 20 21  8]
 [ 1  9  1 11]
 [12  1 11  9]
 [ 9 19 20  3]
 [21 13 10  2]]
This is the final array after substracting the mean of each row from each element in it [[11 20 21  8]
 [ 1  9  1 11]
 [12  1 11  9]
 [ 9 19 20  3]
 [21 13 10  2]]
